-- Migration 046: hipaa_analysis_log identity columns — DDL OWNED BY DB AGENT
--
-- org_source, gate_source, correlation_id were added to compliance.hipaa_analysis_log
-- by the DB agent (commit aebc2ce on their repo) — their migration is authoritative
-- for this table's DDL. This file is intentionally a no-op to avoid duplicate-column
-- errors if applied after their migration already ran.
--
-- Chat agent owns the WRITER: _resolve_gate_org() + INSERT stamping in app/main.py.
-- DB agent to add NOT NULL on user_id/org_slug once both writers comply.
