# Default LLM config (Vertex AI for dev cloud).
version: "default"
provider: "vertex"
model: "gemini-2.5-flash"
options:
  temperature: 0.1
vertex:
  project_id: null  # set via VERTEX_PROJECT_ID env
  location: "us-central1"
