# Production LLM config (Vertex AI / Gemini).
version: "production"
provider: "vertex"
model: "gemini-2.0-flash"
options:
  temperature: 0.1
vertex:
  project_id: null  # set via VERTEX_PROJECT_ID env
  location: "us-central1"
